version: "3"
services:
  yh-metricbeat:
    image: docker.elastic.co/beats/metricbeat:${VERSION}
    container_name: yh-metricbeat
    environment:
      ELASTICSEARCH_HOSTS: '["http://yh-es01:9200"]'
      KIBANA_HOSTS: '["http://yh-kibana:5601"]'
      ELASTICSEARCH_USERNAME: ${ELASTIC_USER}
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - type: bind
        source: ${PWD}/metricbeat/config/metricbeat.yml
        target: /usr/share/metricbeat/metricbeat.yml
        read_only: true
    command: ["--strict.perms=false"]
    restart: always
    networks:
      - elastic
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

networks:
  elastic:
    name: yh-elastic
    driver: bridge